// tslint:disable
/**
 * Lapala-plugins
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GetUserBubbleModel,
    LogDataModel,
} from './';

/**
 * @export
 * @interface IndexModel
 */
export interface IndexModel {
    /**
     * @type {LogDataModel}
     * @memberof IndexModel
     */
    logDataModel?: LogDataModel;
    /**
     * @type {GetUserBubbleModel}
     * @memberof IndexModel
     */
    getUserBubbleModel?: GetUserBubbleModel;
}
