// tslint:disable
/**
 * Lapala-plugins
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MethodHttp,
} from './';

/**
 * @export
 * @interface PluginRequestDataConfig
 */
export interface PluginRequestDataConfig {
    /**
     * @type {string}
     * @memberof PluginRequestDataConfig
     */
    url: string;
    /**
     * @type {number}
     * @memberof PluginRequestDataConfig
     */
    port?: number;
    /**
     * @type {string}
     * @memberof PluginRequestDataConfig
     */
    name: string;
    /**
     * @type {MethodHttp}
     * @memberof PluginRequestDataConfig
     */
    method: MethodHttp;
}
